name: dev-auto

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: clone
      run: git clone https://github.com/atgane/cicd-practice.git
    
    - name: checkout release
      run: git checkout -t remotes/origin/release
    
    - name: auto merge
      run: git merge remotes/origin/dev

    - name: auto push
      run: git push