name: dev-auto

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: checkout dev
      run: git checkout dev

    - name: config
      run: git config --global user.name "atgane"

    - name: config
      run: git config --global user.email "hyper2012@naver.com"

    - name: build
      run: go build ./main.go

    - name: checkout release
      run: git remote set-branches --add origin release 
      
    - name: fetch
      run: git fetch
      
    - name: checkout
      run: git checkout --track remotes/origin/release 

    - name: auto merge release
      run: git merge -X theirs dev --allow-unrelated-histories