name: dev-auto

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: checkout dev
      run: git checkout -t remotes/origin/dev
    
    - name: build
      run: go build ./main.go