name: dev-auto

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Merge
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ github.token }}
        source: 'dev'
        target: 'release'

    - name: Checkout release
      uses: actions/checkout@v3
      with:
        ref: release

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: hyper2012/app:latest


  deploy:
    needs: build
    runs-on: [ self-hosted, label-go ]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Docker run
      run: |
        docker stop go_cicd && docker rm go_cicd && docker rmi hyper2012/app:latest
        docker run -d -p 8080:8080 --name go_cicd --restart always hyper2012/app:latest